services:
  db:
    image: postgres:15-alpine
    container_name: taskapp-db
    environment:
      POSTGRES_DB: taskapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: taskapp-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskapp
    depends_on:
      - db
    ports:
      - "33:3001"

  frontend:
    build: ./frontend
    container_name: taskapp-frontend
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  postgres_data:
