apiVersion: v1
kind: Service
metadata:
  name: taskapp-frontend
spec:
  type: NodePort
  selector:
    app: taskapp-frontend
  ports:
    - port: 80
      # Cambio introducido para redirigir al nuevo puerto interno del frontend no root.
      targetPort: 8080
      nodePort: 30080
